[tools]
go = "1.24.11"
node = "24.12.0"
python = "3.14.2"
fzf = "0.67.0"
ghq = "1.8.0"
ripgrep = "15.1.0"
"npm:@anthropic-ai/claude-code" = "2.0.76"
uv = "0.9.18"
"npm:turbo" = "2.7.2"
gh = "latest"
chezmoi = "latest"
bat = "latest"
"npm:@fission-ai/openspec" = "latest"
pnpm = "latest"
